### ISSUE TITLE
如何添加侧滑删除

### ISSUE THREAD

**Issue by txadf** [nikhilpanju/RecyclerViewEnhanced#10]
很喜欢改控件样式，需要侧滑课以删除和修改的，如何实现，试了下，实现了侧滑删除，但修改那个始终无效了，

**Comment by txadf** [comment]
好奇怪，开始出现空指针异常，后来竟然奇迹般的好了，

**Comment by nikhilpanju** [comment]
Can someone translate this?

**Comment by txadf** [comment]
it comes NullpointerException, when i  make on of the swipe menu as delete the current recyclerview item ,but it appeared sometimes.
