### ISSUE TITLE
How Implement OnSwipeListener?

### ISSUE THREAD

**Issue by krawa** [nikhilpanju/RecyclerViewEnhanced#14]
Please, how Implement OnSwipeListener?
Thanks!

**Comment by nikhilpanju** [comment]
Please go through the ReadMe file. If you have a more specific doubt, raise another issue. I'd be glad to help. Thank you!

**Comment by riki-dexter** [comment]
Hi @nikhilpanju ,
can you explain with a piece of code how to use OnSwipeListener?
Thank you

**Comment by miltonrincon** [comment]
I cant find anything related to the use of OnSwipeListener ihn the readme file. In the RecyclerTouchListener.java this interface is only to be used privately, it cant be used out of this class
