### ISSUE TITLE
Doesn't it provide left swipe direction?

### ISSUE THREAD

**Issue by ghost** [nikhilpanju/RecyclerViewEnhanced#24]
I want to have swipable edit button on left side instead of standard right side. I dont find any way or method to do that. Please help me.

**Comment by nikhilpanju** [comment]
It's currently in the works. It will be released in the next version.

**Comment by pavelpoley** [comment]
@nikhilpanju any news?

**Comment by Vijayadhas** [comment]
@nikhilpanju Could you help me to add Left to Right Swipe??
