### ISSUE TITLE
 some problems

### ISSUE THREAD

**Issue by BelongsH** [nikhilpanju/RecyclerViewEnhanced#6]
I found that when the screen turns off when the swiped becomes ineffective and Viewholder multiplexing effect occurs. 

test environment:
Millet 3 system: 6.0.1

**Comment by harsu-ag** [comment]
This bug occurred in compiling sample project or its implementation.?

**Comment by BelongsH** [comment]
compiling sample project

**Comment by harsu-ag** [comment]
```
 @Override
    protected void onResume() {
        super.onResume();
        mRecyclerView.addOnItemTouchListener(onTouchListener);
    }

```
He probably missed this out in the MainActivity.

**Comment by nikhilpanju** [comment]
harsu-ag is correct. I missed it in onResume(). Added in v1.1

**Comment by NiteshThakor** [comment]
can i make left or right both side swipable recylerview using this library?
its posible so how?
