### ISSUE TITLE
Disable Auto Close

### ISSUE THREAD

**Issue by srolemberg** [nikhilpanju/RecyclerViewEnhanced#9]
It's possible Disable the autoclose of the foreground view when click in itens from OptionView?
Or need help to implement this feature?

**Comment by nikhilpanju** [comment]
This was how it was established initially but it was changed.
Scenario 1:
Click on option -> Something that changes data set
Scenario 2:
Click on option -> Navigate to sub activity -> Change main activity data set -> Go back to main activity

For both these scenarios, a different row/item had it's foreground open after said action was performed.
If you can implement this feature and overcome those scenarios, I'd be more than happy to merge in your PR
